baseURL = "https://millermaskproject.com"
title = "millermaskproject"
theme = "hargo"
languagecode = "en-us"
summaryLength = "20"
paginate = 10
disqusShortname = "millermaskproject"

canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[menu]
    [[menu.main]]
    name = "About"
    weight = 1
    url = "about"

    [[menu.main]]
    name = "Orders"
    weight = 2
    url = "order"

    [[menu.main]]
    name = "Donations"
    weight = 3
    url = "http://help.feedingamerica.org/goto/MillerMaskProject"

    [[menu.main]]
    name = "FAQ"
    weight = 4
    url = "faq"

[params]
    # logo = todo
    home = "Home"
    author = "milldr"
    description = "description todo"
    keywords = "covid,masks,corona"
    email = "millermaskproject@gmail.com"

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
URL = "s3://millermaskproject?region=us-west-2"

[[deployment.matchers]]
# Cache static assets for 20 years. should be good
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
