workflows:
version: 1.0
jobs:
  validate:
    docker:
      - image: milldr/static-site-deployer
    steps:
      - run:
          name: "Validate Cloudformation"
          command: |
            cfn_nag_scan --input-path aws/static-site.yml
  build:
    docker:
      - image: milldr/amazon-brew
    steps:
      - checkout
      - run:
          name: "Deploy or update stack"
          command: |
            aws cloudformation deploy --template-file aws/static-site.yml --stack-name millermaskproject --capabilities CAPABILITY_NAMED_IAM
      - run:
          name: "Deploy static content to S3 with Hugo"
          command: |
            cd ./millermaskproject
            hugo -D
            hugo -v deploy --maxDeletes -1
  test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: "Test url"
          command: |
            curl https://millermaskproject.com
