workflows:
version: 1.0
jobs:
  build:
    docker:
      - image: milldr/amazon-brew
    steps:
      - checkout
      - run:
          name: "Install Hugo"
          command: "brew install hugo"
      - run:
          name: "Set bucket policy"
          command: "aws s3api put-bucket-policy --bucket millermaskproject --policy file://aws/bucket-policy.json"
      - run:
          name: "Deploy static content to S3 with Hugo"
          command: |
            cd ./millermaskproject
            hugo -D
            hugo -v deploy --maxDeletes -1
  test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: "Test url"
          command: |
            curl https://millermaskproject.com
